meta:
  siteName: Miners Online
navigation:
  - title: Home
    url: /
    icon: bi bi-house
  - title: News
    url: /news
    icon: bi bi-newspaper
  - title: Wiki
    url: /wiki
    icon: bi bi-book
footer:
  copyright: "Miners Online - © Samuel Hulme 2017 - 2026. All rights reserved."
  columns:
    - title: Navigation
      links:
        - title: Home
          url: /
          icon: bi bi-house
        - title: News
          url: /news
          icon: bi bi-newspaper
        - title: Wiki
          url: /wiki
          icon: bi bi-book
    - title: Social
      links:
        - title: Discord
          url: https://discord.gg/aeRReEaNnm
          icon: bi bi-discord
        - title: GitHub
          url: https://github.com/minersonline
          icon: bi bi-github
